server:
     port: 8082
     servlet:
          context-path: /sbl
spring:
  profiles:
    active: dev
  jmx:
    default-domain: sbl
  application:
    name: sbl
  thymeleaf:
    prefix: classpath:/template/
    suffix: .html
mybatis-plus:
     configuration:
          #打印sql语句
          log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
mybatis:
  mapper-locations: classpaths:mapper/**/*Mapper.xml