server:
     port: 8082
     servlet:
          context-path: /sbl

spring:
     profiles:
          active: dev
     application:
          name: sbl
--- #开发环境
spring:
     profiles: dev
downloadfilepath:
     profile: /develop

--- #生产环境
spring:
     profiles: pro
downloadfilepath:
     profile: /product
